version: '3.3'
services:
  server:
    build:
      context: server
    depends_on: 
      - mongo
    env_file:
      - dbconfig/.env
    networks:
      - sensorcheck-net
    expose:
        - "8080"
    ports:
        - '8080:8080'
  mongo:
      image: 'mongo:latest'
      container_name: 'mongo'
      env_file:
        - dbconfig/.env
      volumes:
        - ./server/data/mongodb/db:/data/db
        - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      ports:
        - '27100:27017'
      networks:
        - sensorcheck-net

networks:
  sensorcheck-net:
    driver: bridge